### PR TITLE
Load property "Modified" when loading workbook

### LINKED ISSUE #1568: The Property Properties.Modified is not read when loading a Workbook
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No=> No need. I checked the code

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.
=> No need. I checked the code

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

When I load a XLWorkbook the property "Modified" is DateTime.MinValue instead of the documents value.

**What is the expected behavior or new feature?**

The property "Modified" should have the value of the document.
This can be solved in XLWorkbook_Load in SetProperties by adding the following code:
```
            if (p.Modified != null)
                Properties.Modified = p.Modified.Value;
```
**Is this a regression from the previous version?**

I don't think so.

**Code to reproduce problem:**
```c#
[Test]
public void ModifiedRepro ()
{
  // NOTE: arrange
  var now = DateTime.Now;
  using (var workBookForSave = new XLWorkbook ())
  {
    workBookForSave.AddWorksheet ();
    workBookForSave.Properties.Modified = now;
    workBookForSave.SaveAs ("C:\\temp\\bla.xlsx");
  }

  // NOTE: act
  using (var workBookForLoad = new XLWorkbook ("C:\\temp\\bla.xlsx"))
  {
    var modified = workBookForLoad.Properties.Modified;

    // NOTE: assert
    /* this fails with:
      Message: 
        Expected: 2020-11-19 15:35:22.2226398
        But was:  0001-01-01 00:00:00
    */
    Assert.That (modified, Is.EqualTo (now));
  }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

### PR DESCRIPTION
**Pull request by rominator1983**
Closes #1568

### CODE REVIEW

**Review by Pankraty — COMMENTED** [review]
Add a test please. For example, using MemoryStream save a workbook with this property set then load it from that stream and check the property value - this will cover both saving and loading.

**Comment by rominator1983** [comment]
there you go

**Comment by rominator1983** [comment]
I also tested the load/save-behavior of all other properties in the class

**Review by Pankraty — APPROVED** [review]

**Comment by Pankraty** [comment]
Thanks for your contribution! Keep going! =)

**Pull request merged**
