### PR TITLE
Treat warnings as errors

### PR DESCRIPTION
**Pull request by igitur**
Depends on #794

### CODE REVIEW

**Comment by igitur** [comment]
Only once we remove `ValueCached` can we implement this.

**Comment by Pankraty** [comment]
> Only once we remove ValueCached can we implement this.

Not necessarily. If we mark all the methods (test including) where ValueCached is used as [Obsolete] too Visual Studio will be fine with this.

**Comment by igitur** [comment]
`ValueCached` is populated when a file is loaded, so we'll then have to mark basically everything as obsolete.

**Comment by Pankraty** [comment]
> `ValueCached` is populated when a file is loaded, so we'll then have to mark basically everything as obsolete.

Again, not necessarily ) We can populate an internal property and make `ValueCached` to be a mere wrapper for it OR we can add an exception for this particular warning for this part of code (https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning) or project-wide.

**Comment by igitur** [comment]
No, too much effort for something small like this. Let's just park this until later and in the meantime we can fix warnings ourselves instead of forcing them as errors.

**Comment by Pankraty** [comment]
Ehm... I pushed my commit into your branch accidentally. I did not mean it =-)

**Comment by igitur** [comment]
How do you even have access to do that?

**Comment by Pankraty** [comment]
> How do you even have access to do that?

image
So easy 😄

**Pull request merged**
