### PR TITLE
Add new methods for adding pictures that don't require System.Drawing.Bitmap to work

### PR DESCRIPTION
**Pull request by SuNNjek**
Currently adding a picture to a worksheet requires System.Drawing.Bitmap to work. However, the only use for it is reading out format and size of the image.
This PR adds methods that take the format and size as parameters to be passed in. This way, pictures can be added on platforms that don't support System.Drawing.Bitmap, such as UWP, Android and iOS.

### CODE REVIEW

**Comment by Pankraty** [comment]
I've made some changes to reduce code duplication across constructors, but unable to push to your branch. Please, either cherry-pick changes from https://github.com/Pankraty/ClosedXML/commit/35e05e256d25cccf5b2577a7d203f1147778ec1d or set a checkbox "Allow maintainers to change PR"

**Comment by SuNNjek** [comment]
The checkbox should be checked already, at least for me

**Comment by Pankraty** [comment]
My bad, used the wrong SSH key.

**Comment by jahav** [comment]
System.Drawing.Common dependency has been removed in #1805 and if there is a need to be able to load additional formats, it should be implemented through a different https://github.com/ClosedXML/ClosedXML/wiki/Graphic-Engine instead of additional public API. 

Note that the use of image formats other than PNG/JPG is discrouraged:
> A producer that wants interoperability should use one of the following standard formats:
> * image/png ISO/IEC 15948:2003, http://www.libpng.org/pub/png/spec/
> * image/jpeg, http://www.w3.org/Graphics/JPEG
>                                      -- ECMA-376, Part1, §15.2.14

**Pull request closed without merging**
