### PR TITLE
Shift Conditional Formats

### PR DESCRIPTION
**Pull request by b0bi79**
Shift Conditional Formats when inserted rows or columns.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks. Will look at this and your other issues soon.

**Comment by b0bi79** [comment]
@igitur review please my commits.
В последнем коммите я исправил некоторые свои ошибки и те, которые нашёл в ClosedXML.

**Comment by igitur** [comment]
Sorry, all tests have to pass. Please inspect the failing test.

**Comment by b0bi79** [comment]
I want to rework this part, and will make a new pool request soon.

**Comment by igitur** [comment]
Ok, rebase it on the new `develop` branch. I merged a lot of PRs recently.

**Comment by b0bi79** [comment]
of course

**Pull request closed without merging**
