### PR TITLE
WIP: System.Drawing.Common font measurement replacement

### PR DESCRIPTION
**Pull request by jahav**
This PR is an attempt to decrease dependency on System.Drawing.Common by using two different ways for font measurement:
* net40,net46 - keep System.Drawing.Common, it's windows only and will continue to work
* netstandard2.0 - use SixLabors.Fonts library to determine font measure.

I am not happy with having two different implementation, but it seems like best of bad options. Opinions are welcome.

PR is a part of of changes for #1805

### CODE REVIEW

**Comment by igitur** [comment]
If we drop support for net40 and net461 and replace with net472, would that solve the issue?  If so, we should have a discussion about which frameworks we want to support going forward.

**Comment by LeaFrock** [comment]
As net40/net461 is EOL, I think it's not bad to drop them in order to make the maintenance easier. Of course it should be a change of major version(`1.0`?). People who stay on old NFX versions can still use `0.9x`.

`net standard 2.0` is compatible to net462 and above. IMO, `net standard 2.1` , which has more exposed APIs,  is optional but more suitable for future development of this repo.

If so, `System.Drawing.Common` can be totally replaced by `ImageSharp`.

**Comment by igitur** [comment]
> Of course it should be a change of major version(`1.0`?). People who stay on old NFX versions can still use `0.9x`.

Assuming we follow semver, even versions < 1.0 are allowed breaking changes.

**Comment by jahav** [comment]
I am closing this PR in favor of #1866. The other PR is more capable (e.g. EMF file format) and it is more in tune with [Cell dimensions](https://github.com/ClosedXML/ClosedXML/wiki/Cell-Dimensions).

**Pull request closed without merging**
