### PR TITLE
Load data validations from worksheet extensions

### PR DESCRIPTION
**Pull request by sechel**
List data validations referencing a separate worksheet are stored in `WorksheetExtensions`, e.g.
```xml
<extLst>
    <ext uri="{CCE6A557-97BC-4b89-ADB6-D9C93CAAB3DF}"
        xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
        <x14:dataValidations count="1"
            xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
            <x14:dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" xr:uid="{00000000-0002-0000-0100-000000000000}">
                <x14:formula1>
                    <xm:f>ValuesSheet!$A$1:$A$4</xm:f>
                </x14:formula1>
                <xm:sqref>A2</xm:sqref>
            </x14:dataValidation>
        </x14:dataValidations>
    </ext>
</extLst>
```

Currently `ClosedXML` only loads conditional formatting and sparklines from the extension list. This PR adds data validations from extension list.

Addresses this issue: https://github.com/ClosedXML/ClosedXML/issues/1797

### CODE REVIEW

**Comment by sbeca** [comment]
Thanks for this patch @sechel, I've been using it in a custom build of ClosedXML for a bit over a month as I needed the fix to make some spreadsheets function correctly, and it has been mostly working great for me.

The loading works perfectly, but I did start running into some errors when saving/loading spreadsheets multiple times with your patch applied. Specifically, I ran into this exception when going through the save/load cycle more than once:
```
System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
  at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
  at ClosedXML.Excel.XLDataValidations.Delete(IXLDataValidation dataValidation) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/DataValidation/XLDataValidations.cs:line 73
  at ClosedXML.Excel.XLDataValidations.Consolidate()
  at ClosedXML.Excel.IO.WorksheetPartWriter.GetWorksheetDom(Boolean partIsEmpty, WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveOptions options, SaveContext context) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/IO/WorksheetPartWriter.cs:line 1245
  at ClosedXML.Excel.IO.WorksheetPartWriter.GenerateWorksheetPartContent(Boolean partIsEmpty, WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveOptions options, SaveContext context) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/IO/WorksheetPartWriter.cs:line 39
  at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/XLWorkbook_Save.cs:line 335
  at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/XLWorkbook_Save.cs:line 106
  at ClosedXML.Excel.XLWorkbook.Save(SaveOptions options) in /opt/atlassian/pipelines/agent/build/ClosedXML/ClosedXML/Excel/XLWorkbook.cs:line 394
  at ClosedXML.Excel.XLWorkbook.Save(Boolean validate, Boolean evaluateFormulae)
```

This was happening because saving was causing data validations with references to other sheets to get saved both in the standard data validations location as well as the extensions, leading to duplicates.

I have fixed this locally in this commit of mine: https://github.com/sbeca/ClosedXML/commit/5ef446ccde19d9dc96e1345847987b30cc375bb7

This commit adds a new test to capture the multiple save/load cycle issue, as well as the fix for it. This brings the saving of data validations in-line with how Excel does it.

It would be great if you could grab this commit and include it within this PR, so that when it eventually gets merged it has the complete solution for data validation extensions

**Comment by sechel** [comment]
Hey @sbeca, thank you very much for this contribution. I'm in a similar situation. I'm using this in a custom build, too. In fact I was aware of the `save` issue and created this small workaround: 5e252ad3c77a7e3c8d82247da2cf8bb843ee23af. I just hadn't the time to find a sustainable solution. The new changes create conflicts with current `develop` but there are changes upstream that prevent me from merging at the moment.

**Comment by sechel** [comment]
Hey @sbeca. I have updated my version with your changes. I'm seeing exceptions when running tests along the lines of
```
System.ApplicationException : Part /xl/worksheets/sheet7.xml, Path /x:worksheet[1]/x:dataValidations[1]: The element has incomplete content. List of possible elements expected: <[http://schemas.openxmlformats.org/spreadsheetml/2006/main:dataValidation>.](http://schemas.openxmlformats.org/spreadsheetml/2006/main:dataValidation%3E.)
Part /xl/worksheets/sheet9.xml, Path /x:worksheet[1]/x:dataValidations[1]: The element has incomplete content. List of possible elements expected: <[http://schemas.openxmlformats.org/spreadsheetml/2006/main:dataValidation>.](http://schemas.openxmlformats.org/spreadsheetml/2006/main:dataValidation%3E.)
  Stack Trace:
     at ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at EasyGen.Excel.Tests.ReportsTests.TestINDSaveDocument1() in C:\Agent\_work\19\s\EasyGen\EasyGen.Excel.Tests\Reports.Tests.cs:line 91
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Maybe that does ring a bell, otherwise I'll have to dig into that and see what it may be.

**Comment by sbeca** [comment]
Looks like this PR has some conflicts that would stop it from being merged, so you might just need to rebase on top of develop to get things working correctly.

**Comment by jahav** [comment]
Closing in favor of #2203 because this PR doesn't have *Allow edits from maintainers* or some other setting required to make changes.

The reason why tests didn't pass was that worksheet/datavalidations require at least one child, it can't be empty element with no children.

**Pull request closed without merging**
