### PR TITLE
Fix Issue #325

### PR DESCRIPTION
**Pull request by DmitriyPotapov**
#### Questions:
- Is there a blog post? - NO
- Does the knowledge base need an update? - NO
- Does this add new (C#) dependencies? - NO

- [x] C# Code Review: @csreviewer
- [x] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by igitur** [comment]
Pleased explain what `TryGetExcelSerialDate` does that was lacking before. Is this related to the issue of months > 12? If not, it should go in a separate PR.  Again, a simple unit test should illustrate the problem.

**Comment by DmitriyPotapov** [comment]
> You have to account for negative months too. I think =DATE(2017,-5,15) works in Excel.

> Also months greater than 24.

In this case, the function (_**private static object Date(List<Expression> p)**_) returns the correct value

```
in Excel Worksheet i have a formula:
=DATE(A2;B2+D2;C2)
My cell values is:

A2 = 2017;
B2 = 10;
C2 = 25;
D2 = -5;
```

In this case, too

``` 
in Excel Worksheet i have a formula:
=DATE(A2;B2+D2;C2)
My cell values is:

A2 = 2017;
B2 = 10;
C2 = 25;
D2 = -5;
```
I think the problem lies in the parser of the excel formulas, not in this functions.


Function **TryGetExcelSerialDate** convert integer value passed from cell formula to DateTime value, i added this function because in my cases, function TryGetValue did not return any value and throw the exception **_Cannot convert cell value to System.DateTime_**.  When there are no formulas in a cell with a date, the value is returned by **_TryGetStringValue_** function....

**Comment by igitur** [comment]
Make D2=-15

**Comment by DmitriyPotapov** [comment]
Yes, in case when D2 = -15 or less, date calculated wrong. I update function for negative month.
```c#
 private static object Date(List<Expression> p)
        {
            var year = (int)p[0];
            var month = (int)p[1];
            var day = (int)p[2];
            int tempMonth = 0;

       
            if (month > 12)
            {
                tempMonth = month - 12;
                var tempDate = new DateTime(year, 12, day).AddMonths(tempMonth);
                return (int)Math.Floor(new DateTime(tempDate.Year, tempDate.Month, tempDate.Day).ToOADate());
            }
            if (month < 0)
            {
                month--;
                tempMonth = month;
                var tempDate = new DateTime(year, 1, day).AddMonths(tempMonth);
                return (int)Math.Floor(new DateTime(tempDate.Year, tempDate.Month, tempDate.Day).ToOADate());
            }
            return (int)Math.Floor(new DateTime(year, month, day).ToOADate());
        }
```

**Comment by igitur** [comment]
and if `D2=50`?

**Comment by DmitriyPotapov** [comment]
> and if `D2=50`?

I tested such values:

1.  `D2 = -50`
2. `D2 = -501`
3. `D2 = 50`

In all cases, the function returned the correct values

**Comment by DmitriyPotapov** [comment]
In case where day or month has sub formula `DATE(A2;B2+F2;C2+D2)` i have same exception. 
In latest commit a added code for handle this

**Comment by igitur** [comment]
#333 is a cleaner fix.

**Pull request closed without merging**
