### PR TITLE
Change target framework to 4.0

### PR DESCRIPTION
**Pull request by Pankraty**
Related pull request #650, #659 

Deep thanks to everyone for the help! I finally did it )

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by vbjay** [comment]
That is why I said you should run update-database -reinstall.

**Comment by vbjay** [comment]
LMAO. Auto correct file the win. Update-packages -reinstall

**Comment by vbjay** [comment]
My phone is fighting me hard today.

**Comment by vbjay** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages

**Comment by igitur** [comment]
Please test this with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.800/artifacts

**Pull request merged**
