### PR TITLE
fixed null reference exception

### PR DESCRIPTION
**Pull request by vansli**
improved null check when loading pivot tables

### CODE REVIEW

**Comment by igitur** [comment]
I think the null reference exception is addressed in #179 . Apply that PR and see if it fixes your issue, please.

**Comment by igitur** [comment]
Also, you last commit, related to the NuGet package, should be a separate pull request and you have to ensure that the CI unit test pass. I'd recommend you chat to @Pyropace first anyway. He is the package maintainer and as far as I recall the CI already handles the NuGet packaging.

**Comment by vansli** [comment]
Hi,

actually,  my last commit should not be in the pull request. It will probably not build on a "normal"  environment as it needs a special VS addon.
It was mainly for our build process as I need a working package for the project and I don't know when you'll release the next update.

This was actually my first pull request for an open source project...  ☺️

Great library,  btw. We switched from EPPlus as we faced some issues there. We need something to read excel files and ClosedXML works fine so far,  even though I understand that the main usage is writing files,  right?

Regards,
Arjen

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by igitur** [comment]
Welcome to the open source community. Please merge #179 into your codebase and see if it fixes this issue.

**Pull request closed without merging**
