### PR TITLE
Support ConditionalFormat DataBar like Office 2010

### PR DESCRIPTION
**Pull request by JavierJJJ**
This modify ConditionalFormat to support Databar like Office 2010 with diferent color for negative values.

### CODE REVIEW

**Comment by igitur** [comment]
Please ensure that all tests pass.

**Comment by JavierJJJ** [comment]
I Dont know how to download lastest code repository because the branch develop dont compile

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by igitur** [comment]
I'll reopen the pull request once the tests pass.

**Comment by igitur** [comment]
Also, the `develop` branch should compile without problems. Please do a fresh pull from the repository and if you are sure there is a problem, create a separate issue for it.

**Comment by patrickkelleyintertek** [comment]
Can we please reopen this pull request?  This feature would be nice to have implemented.  Can someone please test?

**Comment by igitur** [comment]
I'll reopen it if the review comments are addressed.

**Comment by patrickkelleyintertek** [comment]
I copied the changes that @JavierJJJ committed in regards to the negative bar.  I excluded the changes he committed that were multi-threading changes.  It ran just fine with no issues with the tests.  Would you like me to create a new pull and commit changes to that?

**Comment by igitur** [comment]
@patrickkelleyintertek Yes, create a new PR based on the `develop` branch. Ensure you add a unit test for any functionality added. Thanks

**Comment by JavierJJJ** [comment]
I create a modified versión with last code from develop with issue #431 that compile success.

**Pull request closed without merging**
