### PR TITLE
Pivot formatting adding/loading/saving

### PR DESCRIPTION
**Pull request by b0bi79**
#### What's this PR do?
PR adds formatting (styles) to the pivot table.

#### How should this be manually tested?
Run test XLPivotTableTests.PivotFieldFormatsTest.

#### Screenshots (if appropriate)
2018-06-04 10-39-17 microsoft excel - pvt xlsx

### CODE REVIEW

**Comment by igitur** [comment]
Thanks. I'm going to look at the changes to the API first. Let's discuss that first and then we can get to the implementation.

**Comment by b0bi79** [comment]
Yes, I also wanted to discuss the API, how best to implement it.

**Comment by igitur** [comment]
Please rebase on `develop`.

**Comment by igitur** [comment]
Thanks @b0bi79, but please rebase develop, not merge.

**Comment by b0bi79** [comment]
Rebased

**Comment by b0bi79** [comment]
@igitur Sorry Francois, can you review this PR?

**Comment by igitur** [comment]
Ok, I'd like to start to talk about the API. 

```c#
pt.PivotFormats.Add(b => { b.ForSubtotal(row).Style.Fill.BackgroundColor = XLColor.Blue; });
pt.PivotFormats.Add(b => { b.ForLabel(clmn).Style.Fill.BackgroundColor = XLColor.Amber; });
pt.PivotFormats.Add(b => { b.ForHeader(clmn).Style.Font.FontColor = XLColor.Yellow; });
pt.PivotFormats.Add(b => { b.ForGrandRow().Style.Font.FontColor = XLColor.VenetianRed; });
pt.PivotFormats.Add(b => {
    b.ForData(row)
    .AndWith(clmn, v=>v.ToString() == "May")
    .ForValueField(numberOfOrders).Font.FontColor = XLColor.Green;
});
```

One would have to use those lambda functions (`b => ...`) to set the formats. This is a bit different to the rest of ClosedXML's API. Sorry, but it feels out of place.

Can this not be replaced with something like this?
```c#
pt.PivotFormats.Subtotal(row).StyleFill.Backgroundcolor = XLColor.Blue;
pt.PivotFormats.Label(clmn).Style.Fill.BackgroundColor = XLColor.Amber;
pt.PivotFormats.Header(clmn).Style.Font.FontColor = XLColor.Yellow;
pt.PivotFormats.GrantTotal.Style.Font.FontColor = XLColor.VenetianRed;
pt.PivotFormats.Data(row)
    .AndWith(clmn, v=>v.ToString() == "May")
    .ForValueField(numberOfOrders)
    .Style.Font.FontColor = XLColor.Green;
```

or even 
```c#
row.PivotFormat.SubTotals.StyleFill.Backgroundcolor = XLColor.Blue;
clmn.PivotFormat.Labels.Style.Fill.BackgroundColor = XLColor.Amber;
clmn.PivotFormat.Headers.Style.Font.FontColor = XLColor.Yellow;
pt.PivotFormat.GrantTotal.Style.Font.FontColor = XLColor.VenetianRed;
row.PivotFormat.Data(clmn, v=>v.ToString() == "May")
    .ForValueField(numberOfOrders)
    .Style.Font.FontColor = XLColor.Green;
```

I haven't gone in depth, but this was the first thing I noticed. So before we go into the implementation, I would like to have the discussion around the API.

And sorry for the delay. From what I can see, Pivot Tables need a major overhaul anyway.

**Comment by b0bi79** [comment]
Конечное построение формата выполняется в методе PivotFormats.Add(). Если вы предложите способ построения формата без лямбды, то я смогу это переделать.

**Comment by b0bi79** [comment]
The final building of the format is performed in the PivotFormats.Add() method. If you can offer a way to build a format without a lambda, then I can change it API.

**Comment by igitur** [comment]
Yup, digging deeper into this is what I've been planning, and why the review of this is delayed. The 0.94 changes have taken up a lot more time than expected. 0.95 will focus on pivot table improvements, so we'll get this in for them, promise.

**Comment by igitur** [comment]
Do you know how to do these pivot table formats in pure Excel, for example to set an entire field's format? If I format the pivot table's cells in Excel, and save the file, then it creates a whole lot of individual pivot format elements each referring to the individual cells.

**Comment by igitur** [comment]
Superceded by #1129

**Pull request closed without merging**
