### PR TITLE
Excel functions

### PR DESCRIPTION
**Pull request by pichardoSoftware**
#52 Changes
## 
- Logical
  - IfError
- Information
  - IsBlank
  - IsEven
  - IsLogical
  - IsNonText
  - IsNumber
  - IsOdd
  - IsText
  - N
  - Type
  - PENDING: How to handle Array Types?

**Each method has tests on the respective test class**

### CODE REVIEW

**Comment by igitur** [comment]
Thanks! I'll have a look at it later.

**Comment by igitur** [comment]
PS: You can earn a T-Shirt if you submit at least 4 PRs by the end of October. check https://hacktoberfest.digitalocean.com/

**Comment by pichardoSoftware** [comment]
Yeah, thanks. I Will keep working on the Information class, currently I am waiting for the CalcEngine Exceptions.

**Comment by Pyropace** [comment]
These looks good Thank you 👍

**Pull request merged**
