### PR TITLE
Fix for issue #1187

### PR DESCRIPTION
**Pull request by TheonTech**
#### What's this PR do?
Fixes issue #1187 
#### Where should the reviewer start?
line 34 of XLCFCellIsConverter.cs
#### How should this be manually tested?
-set OS Formats and Location to French (France) and France respectively.
-using ClosedXML, create a spreadsheet that creates a conditional format using a number. 
   Specific example is: 
`ws.Cell(r,2).AddConditionalFormat().WhenEqualOrLessThan(-98.00002f).Font.SetFontColor(XLColor.LightGray);`
-observe that the conditional format is inserted with quotes and has other side effects (ref FrenchSpreadsheet.xlsx attached to issue #1187)
-apply this fix
-observe that the conditional format is now created correctly.

#### Any background context you want to provide?
We actually discovered this bug about 5 years ago. At the time, we submitted a bug report but we also downloaded the source, fixed the bug, and have been using our custom version of ClosedXML ever since. I have recently been refactoring our shared libraries to .netstandard and decided to try using the updated version of ClosedXML from NuGet. However, our testing has revealed that this bug still exists which is why I am submitting this pull request.

#### Questions:
- Is there a blog post? No
- Does the knowledge base need an update? No
- Does this add new (C#) dependencies? No

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by igitur** [comment]
Thanks for the contribution so far. Can you olease add some unit tests? You can have a look at the other conditional format unit tests for a good starting point.

**Comment by TheonTech** [comment]
I would like to do that but I am not sure how I would emulate the OS being set to French.
Also, I am currently in crunch mode for a May 10 release of our product so it will be after that before I can look into adding any unit test(s).

**Comment by igitur** [comment]
There are several tests that first set the current culture before continuing. You can use ` Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");` to do this, but adjust for the required culture name. (French, you said?)

**Comment by Pankraty** [comment]
Replaced with #1245

**Pull request closed without merging**
