### PR TITLE
Allow for custom themes in tables.  Fixes Codeplex 9499

### PR DESCRIPTION
**Pull request by vbjay**
Excel files with custom table theme fail to open because enum.parse can't find that value.

### CODE REVIEW

**Comment by vbjay** [comment]
See https://closedxml.codeplex.com/workitem/9499

**Comment by igitur** [comment]
I think a type safe enum pattern might be a better solution rather than changing to a string type.

**Comment by vbjay** [comment]
I don't think you see the problem.  If I do a enum.tryparse solution, it will still resolve to an unknown predefined value.  Using a string allows for any value and I left the enum for the standard ones.

**Comment by vbjay** [comment]
I realize we need to update it to allow for custom table theme creation and such.  This pull request just makes it so it won't throw an exception when loading a spreadsheet like it does now.

**Comment by vbjay** [comment]
image

image

**Comment by Pyropace** [comment]
Great do you have a sample test file, I would like to create a unit test for this before merging 

Thanks

**Comment by vbjay** [comment]
Follow the codeplex link.

**Comment by igitur** [comment]
Check out #7 , which implements a type-safe enumeration pattern and also opens the door for future development for having custom table themes.

**Comment by Pyropace** [comment]
Hi Vbjay, 

Thank you again for the PR, we decide to go with igitur PR #7 . i will close this PR, looking forward to your future PRs

**Pull request closed without merging**
