### PR TITLE
Update XLCell.MergedRange to use GetIntersectedRanges

### PR DESCRIPTION
**Pull request by igitur**
As discussed in #843 . The new way is more efficient, right, @Pankraty ?

### CODE REVIEW

**Comment by Pankraty** [comment]
Yes, especially when there are plenty of merged ranges

**Comment by igitur** [comment]
> Maybe do the same for conditional formats and data validation rules

To which lines are you referring?

**Comment by Pankraty** [comment]
On the other hand, the effect of it will be hardly noticable (in contrast to `MergedRange` optimization)

**Comment by igitur** [comment]
Ready for review. Last one for 0.93

**Pull request merged**
