### PR TITLE
Explicitly set document type on saving (#1375)

### LINKED ISSUE #1375: Changing SpreadsheetDocumentType
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

develop branch

**What is the current behavior?**

If you open an xltx file you can only save it as xltx.
The SpreadsheetDocumentType doesn't get changed and is a private field in the workbook class.

**What is the expected behavior or new feature?**

You should be able to open an xltx file and save it as xlsx.

**Did this work in previous versions of our tool?  Which versions?**

No

### PR DESCRIPTION
**Pull request by Pankraty**
Fixes #1375

### CODE REVIEW

**Comment by igitur** [comment]
Should we support saving as other types?

**Comment by Pankraty** [comment]
I don't see why not. Having xltx used as a template, it is natural to have an ability to save it as a workbook. And vice versa - to create a template from a given workbook.

**Review by igitur — APPROVED** [review]

**Comment by thekokii** [comment]
are we missing something or this didn't make it to release?

**Comment by igitur** [comment]
This is released. If you encounter a bug in this regards, please open a new issue.

**Comment by thekokii** [comment]
Yes I can see it now, but isn't this achievable saving your excel as memorystream? We would like to open an .xlsm and later save it without the macro as .xlsx but returning it as a memorystream. Is this somehow achievable or a temporary file is needed?

**Comment by chrisjshields** [comment]
Is it possible to add this feature when saving a file to a stream too?

I can potentially add it and create a pull request if need be.

**Comment by chrisjshields** [comment]
Looking through the source, it still does not seem possible to actually change the SpreadsheetDocumentType, it is simply set when the spreadsheet is originally loaded. So I guess you would need to save the workbook as an xlsx file, reload it and save it again?

**Pull request merged**
