### PR TITLE
Issue175 parse commas in print area

### PR DESCRIPTION
**Pull request by andrewkress**
Passes all current tests.
Added test to load file (Misc\LoadSheetsWithCommas.xlsx) that would cause an index out of bounds exception if this change were not implemented.
If formatting or any other standards need  to be modified to fit the project, let me know and I can amend.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks for the contribution, but please use C#6 syntax. You'll notice the CI build failed because you used string interpolation.

**Comment by andrewkress** [comment]
I see that.  New to Github, did it magically rerun after I pushed the commit?

**Comment by igitur** [comment]
Yes, it runs automatically. I'll review the PR in detail next week.

**Comment by igitur** [comment]
The `XLParser` approach isn't going to happen soon, so I'm going to go ahead with this PR. Would you mind resolving the conflicts?

**Comment by andrewkress** [comment]
should be resolved now.

**Comment by clinchergt** [comment]
#263 closes this

**Pull request closed without merging**
