### PR TITLE
Implement loading of workbook theme colors

### PR DESCRIPTION
**Pull request by sbeca**
Currently, ClosedXML saves theme colors that get set by ClosedXML code, but it doesn't currently load theme colors from Workbook files. Instead, ClosedXML currently hardcodes the theme colors with the the following code:
```csharp
        private void InitializeTheme()
        {
            Theme = new XLTheme
            {
                Text1 = XLColor.FromHtml("#FF000000"),
                Background1 = XLColor.FromHtml("#FFFFFFFF"),
                Text2 = XLColor.FromHtml("#FF1F497D"),
                Background2 = XLColor.FromHtml("#FFEEECE1"),
                Accent1 = XLColor.FromHtml("#FF4F81BD"),
                Accent2 = XLColor.FromHtml("#FFC0504D"),
                Accent3 = XLColor.FromHtml("#FF9BBB59"),
                Accent4 = XLColor.FromHtml("#FF8064A2"),
                Accent5 = XLColor.FromHtml("#FF4BACC6"),
                Accent6 = XLColor.FromHtml("#FFF79646"),
                Hyperlink = XLColor.FromHtml("#FF0000FF"),
                FollowedHyperlink = XLColor.FromHtml("#FF800080")
            };
        }
```

This hardcoding leads to incorrect theme colors being used most of the time as the default theme colors in recent versions of Excel have changed from the above, leading to a disconnect between what is shown in Excel and what ClosedXML uses.

This PR implements loading of theme colors from Workbook files.

Fixes some aspects of https://github.com/ClosedXML/ClosedXML/issues/2075

### CODE REVIEW

**Comment by jahav** [comment]
Hi, if there will be time in [0.103](https://github.com/ClosedXML/ClosedXML/discussions/2112), I will look at it, but it's more likely it will be in 0.104.

**Comment by sbeca** [comment]
No problem. The changes I made in this PR are quite simple so it hopefully won't take you long to review when you have time

**Comment by jahav** [comment]
@sbeca  Thanks. I have added a function to parse colors in `ST_HexColorRGB`, because I am not too fond of `XLColor.FromHtml`. It has unclear format requirements, name is misnomer (it expects alpha as first, but HTML has it as last component).

**Comment by sbeca** [comment]
No worries. Thanks for the review and merge

**Comment by ajimenezcu** [comment]
Hello,
I am working on a project where I need to load the theme colors being used by my Excel workbook. The problem is that it always loads the default colors, rather than the ones specified in the Excel file.

I am using the latest version available on NuGet for Visual Studio 2022. Do you know if this issue has been resolved in later versions, as mentioned in the thread? And do you have any information on when these changes will be implemented in the Visual Studio NuGet package?

Thank you, and best regards.

**Pull request merged**
