### PR TITLE
Update ClosedXML.csproj

### PR DESCRIPTION
**Pull request by jeromep01**
Forced to DocumentFormat.OpenXML 2.9.1 !

### CODE REVIEW

**Comment by Pankraty** [comment]
Any particular reasons?

**Comment by jeromep01** [comment]
Yes,

i use this package in many of our librairies (domain+dataaccess) and the
ClosedXML.
I want to follow all packages to the newer version all times, i needed to
upgrade OpenXML.
When i run, i encounter an assembly loader exception due to mismatch
between CloseXML and OpenXML versions (both 2.7.2 and 2.9.1).

Best regards

**Comment by igitur** [comment]
Please see the discussion at #1310 . You should be using the correct binding redirects.

**Comment by Pankraty** [comment]
I am afraid, with this fix many thousand other developers will be forced to upgrade their dependencies too. And I bet they won't be happy with this.

Try to configure binding redirects in your project instead (https://docs.microsoft.com/en-US/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by Pankraty** [comment]
@igitur was faster than me :)

**Pull request closed without merging**
