### PR TITLE
Ensure correct totals row formula format for fields with spaces, single quotes and hashes

### PR DESCRIPTION
**Pull request by igitur**
- Ensure correct totals row formula format for fields with spaces, single quotes and hashes
- Make table names case insensitive

### CODE REVIEW

**Comment by healkar01** [comment]
I just downloaded

Install-Package ClosedXML -Version 0.93.0-beta1

and I am still getting the error for a column titled #CAAS Reporting

If I eliminate the #, I do not get the error.  Are we sure that this made it into this release?

**Comment by igitur** [comment]
I'm sure, but I'll double check. Can I use the same file that you provided in #773?

**Comment by healkar01** [comment]
I think I deleted the file... you can use the corrected code that you provided, but change the column name.

Thanks!

**Comment by igitur** [comment]
@healkar01 This is the unit test that I added to test the fix for #773. It currently passes. If something is failing on your side, please update the unit test to replicate the issue.

```c#
[Test]
public void TotalsFunctionsOfHeadersWithWeirdCharacters()
{
    var l = new List<TestObjectWithAttributes>()
    {
        new TestObjectWithAttributes() { Column1 = "a", Column2 = "b", MyField = 4, UnOrderedColumn = 999 },
        new TestObjectWithAttributes() { Column1 = "c", Column2 = "d", MyField = 5, UnOrderedColumn = 777 }
    };

    using (var wb = new XLWorkbook())
    {
        var ws = wb.AddWorksheet("Sheet1");
        ws.FirstCell().InsertTable(l, false);

        // Give the headings weird names (i.e. spaces, hashes, single quotes
        ws.Cell("A1").Value = "ABCD    ";
        ws.Cell("B1").Value = "   #BCD";
        ws.Cell("C1").Value = "   as'df   ";
        ws.Cell("D1").Value = "Normal";

        var table = ws.RangeUsed().CreateTable();
        Assert.IsNotNull(table);

        table.ShowTotalsRow = true;
        table.Field(0).TotalsRowFunction = XLTotalsRowFunction.Count;
        table.Field(1).TotalsRowFunction = XLTotalsRowFunction.Count;
        table.Field(2).TotalsRowFunction = XLTotalsRowFunction.Sum;
        table.Field(3).TotalsRowFunction = XLTotalsRowFunction.Sum;

        Assert.AreEqual("SUBTOTAL(103,Table1[[ABCD    ]])", table.Field(0).TotalsRowFormulaA1);
        Assert.AreEqual("SUBTOTAL(103,Table1[[   '#BCD]])", table.Field(1).TotalsRowFormulaA1);
        Assert.AreEqual("SUBTOTAL(109,Table1[[   as''df   ]])", table.Field(2).TotalsRowFormulaA1);
        Assert.AreEqual("SUBTOTAL(109,[Normal])", table.Field(3).TotalsRowFormulaA1);
    }
}
```

**Pull request merged**
