### PR TITLE
Update OpenXML SDK to 3.0.

### PR DESCRIPTION
**Pull request by jahav**
Quick update of source code to reflect changes in OpenXML SDK 3.0. It requires net462 and `System.IO.Packaging` 8.0.0.

One test fails (`SavingTests.SavesAsProperSpreadsheetDocumentType`) which was caused by https://github.com/dotnet/Open-XML-SDK/issues/1615. That should be fixed in 3.1 that should be done soon, only [one issue remains for 3.1 milestone](https://github.com/dotnet/Open-XML-SDK/milestone/10).

### CODE REVIEW

**Comment by twsouthwick** [comment]
I should have a v3.0.1 with the fix available in a couple of days (hopefully tomorrow, but to set expectations a few days).

Let me know if you find any other issues with v3 as you roll it out - I'll try to address any regressions :)

**Comment by twsouthwick** [comment]
v3.0.1 is available on nuget with the requested fix - please give it a try

**Comment by twsouthwick** [comment]
>  It requires net462 and System.IO.Packaging 8.0.0.

The supported TFMs are still the same. We support .NET Framework 3.5+, .NET Standard 2.0, .NET Core/5+

**Comment by twsouthwick** [comment]
You may be seeing a change in the support of System.IO.Packaging; however, on framework it never actually did anything and type forwarded to WindowsBase.dll

**Comment by jahav** [comment]
@twsouthwick Thanks! Great work. 

Test passes. I am looking forward to leverage the new `IPackage` and I think I there were few malformed relationship URIs bugs over the years, so that will be really nice to check out too.

**Pull request merged**
