### PR TITLE
Update OpenXmlHelper.cs

### PR DESCRIPTION
**Pull request by behardikjoshi**
use of dynamic gives RuntimeInternal compiler exception while binding dynamic operation as c# is type safe language so use of dynamic must be exceptional.

### CODE REVIEW

**Comment by Pankraty** [comment]
Did you experience any issues with this or you just do not like dynamics? This is a private method called from public methods having strongly-typed signatures which makes it quite hard to misuse the method.
Out of two evils - a risk of incorrect usage of the private method or a code duplication - I chose the first. You propose the opposite. So I wonder why.

**Comment by 06Hardik** [comment]
It gives Runtime internal compiler exception "unexpected exception while binding dynamic operation" during compilation.

IDE: Microsoft visual studio code insider.
Version: 1.38.0

.net core version 2.1.501

**Comment by Pankraty** [comment]
This is strange. It works fine for me and all the other developers, as well as for the AppVeyor. Try to upgrade .net core SDK and see if the problem has gone.

**Comment by igitur** [comment]
Yes, I think an issue needs to be opened first. Please do so and complete
the full template so that we can reproduce the problem. Thanks.

**Comment by igitur** [comment]
@06Hardik Please provide a reproducible test case that illustrates the compilation problem. Else we'll unfortunately have to close this.

**Comment by justcode0012** [comment]
The usage of dynamics objects is a problem for me too.
I want to use ClosedXML in Microsoft SharePoint. Because of a legacy switch in the web.config the following exception occurs when opening an excel-file: "Dynamic operations can only be performed in homogenous AppDomain."
I use a simple excel file with some tables and colored cells.

See the following stackoverflow entry which targets the same problem:
https://stackoverflow.com/questions/5541143/legacycasmodel-true-and-dynamic-data-operations

**Comment by igitur** [comment]
@justcode0012 Are you saying that you have no ability to remove the `<trust legacyCasModel="true" />` line in your web.config?

**Comment by justcode0012** [comment]
@igitur Not really. Even if it does not breaks other components of Micorosoft SharePoint (which i don't know because SharePoint has a lot of feautures), it negatively affects the official vendor support.
Quote from an blog post:

> You shouldn’t change it because of backward compatibility and dependancy reasons we need that. Disabling this property cause anomalies.
Please be aware meaning of NOT SUPPORTED ,does not mean your SharePoint not work. It may work but  we may not give support unless you rollback your changes or can not forseen any other anomalies .

For the people how are more familiar with SharePoint: This problem affects only classic "farm solutions". Because i'am maintaining/extending an legacy solution i'am affected.

**Comment by igitur** [comment]
@Pankraty In light of this, I think we should revert the use of `dynamic`. This seems to be a genuine case where this is a problem.

**Comment by Pankraty** [comment]
Agree

**Comment by behardikjoshi** [comment]
Thanks for considering the suggestion

**Pull request closed without merging**
