### PR TITLE
#548 conditions for strings, #53 improving MULTINOMIAL function, implementing SEC

### PR DESCRIPTION
**Pull request by jongleur1983**
#### What's this PR do?
improve wildcard pattern matching for string conditions:
- support ? wildcard
- support escaping wildcards
- support the empty string as a condition
- cover special cases with unit tests

- the MULTINOMIAL now throws the correct Exceptions as Excel does, when negative values or non-numerical values are given.
- implementing SEC function
- COUNTIF is fixed to support the empty string as a condition.

#### Where should the reviewer start?
Sorry to mix two different things in this PR, but it built on each other because I stumbled over #548 while implementing functions and unit tests.

I think, the PR should be reviewed in three parts:

1. The improvements tackling #548 are covered in the CalcEngineHelper.cs.
2. SEC as additional function and the improvements of MULTINOMIAL are implemented in MathTrig.cs, while corresponding unit tests are in MathTrigTests.cs
3. The fix for CountIf relies on the changes from (1) (CalcEngineHelper), but is completed in Statistical.cs, corresponding tests are located in StatisticalTests.cs of course.

#### How should this be manually tested?
check with the behaviour of Excel ;)
#### Any background context you want to provide?
I stumbled over two more problems I couldn't yet solve, but I don't think, these should be blocker for the PR:

1. Excel can deal with really big numbers. As I know from the past (not sure about the current state) it tended to be unprecise for really big or small numbers. With that in mind it could be that Excel does most calculations in floating point arithmetics, probably in `double` values, rounding afterwards. Currently most functions in ClosedXML are implemented based on interger or long and I found some cases where the Excel crunched much higher numbers than the ClosedXML implementation.
2. For formulas with a range covering a complete column (like A:A) the results differ. I tried a unit test for COUNTIF(A:A, ""), counting all empty values in column G. ClosedXML as well as Excel itself return "very" high numbers, but the exact numbers are different. Guessing again I assume the result is the number of supported lines, which would mean, even Excel versions might not behave equally here.

#### Questions:
- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by igitur** [comment]
Tests failing. But more importantly, please submit a separate PR for each logical change.

**Comment by jongleur1983** [comment]
okay.
I worked at both parts combined, and the entire PR is still limited on the one hand, so it was worth a try ;)
Going to split into two PRs then, https://github.com/ClosedXML/ClosedXML/pull/555 being the first, tackling the expression parser issue #548 alone.

**Comment by igitur** [comment]
So this PR can be closed?

**Comment by jongleur1983** [comment]
I'm not sure: can I still comment on a closed PR later?
This one is obsolete of course because of your request to split it, but it's not completely split yet, so even when closing it I would like to document that split here.
If I can comment here to link the next PR(s) as well, feel free to close it now, else I'd close it once I have moved the other parts.

**Comment by igitur** [comment]
Ok, keeping this open. Just reference this issue in other PRs / issues and let me know when you feel all issues here are addressed.

**Pull request closed without merging**
