### PR TITLE
Fixed the error that caused the massive amounts of System.MissingMet…

### PR DESCRIPTION
**Pull request by charlie-work**
Fixed the error that caused the massive amounts of System.MissingMethodException: Method not found messages.  This also speeds up the process considerably.

This is in reference to issue #1545.  The problem mentioned occurs because ExcelNumberFormat does not support an empty or null string for formatting.  By not passing the empty string as a format, this is avoided.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks for the contribution. A few things: please add a unit test to ensure that we don't ever undo this fix. Also ensure that all current unit tests pass. I see a few are now failing.

**Comment by igitur** [comment]
Just curious... are you not running the unit tests on your own machine before pushing the changes?

**Comment by charlie-work** [comment]
it doesn't run with what i pulled from the repo. also, no idea how to do these so...  i've never written unit tests or anything. no idea how to do that. :/

**Comment by charlie-work** [comment]
i can't get this to pass with your other tests. it works fine on my machine. so i'll just abandon your nuget package and keep my changes local.

**Comment by igitur** [comment]
I can try to help, but so far nobody has been able to provide a simple reproducible test case to show me exactly what the issue is. If you open a new issue and fill in the issue template exactly as requested, then I can inspect.

**Comment by charlie-work** [comment]
ok. i'll open a bug report

**Comment by Murphybro2** [comment]
Was this fix ever committed? I can't seem to find it in use anywhere..

**Comment by charlie-work** [comment]
not my fix.  i don't know how to write unit tests to satisfy their needs.  i just make the changes to my local package and uploaded to my private nuget server.

**Pull request closed without merging**
