### PR TITLE
Add attribute to ignore column

### PR DESCRIPTION
**Pull request by igitur**
Related to issue #205

### CODE REVIEW

**Comment by albinsunnanbo** [comment]
While we're at it adding attributes a Name Attribute that takes precedence over `[Display(Name = "Column name")]` would be useful.
If often use the same model for displaying lists in ASP.NET as for exporting to Excel, but sometimes I want to tweak the Excel export a bit. Hiding columns is one tweak, changing the name (e.g. to an abbreviation) is another. If I recall correctly there is a column order attribute

There are lest two possible API styles for this.
One is different Attributes:

    [Ignore]
    [Order = 2]
    [Name = "FooBar"]
    public string String1 { get; set; }

The other is to have an attribute with named parameters, like

    [XLColumn(Ignore = false, Order = 2, Name = "FooBar")]
    public string String1 { get; set; }

Both have their benefits, but I have a personal preference towards the second.
I think it gives better discoverability of available options. If you have found the XLColumn attribute intellisense will give you all possible options you can set as named attributes.

**Comment by vbjay** [comment]
I agree. Ignore is too comon and vague. I like the XL part of the
attribute. Makes it clear that it is Excel related.

**Comment by albinsunnanbo** [comment]
The question is how to handle the `ColumnOrderAttribute`. Refactor and move to a named parameter of a `XLColumn` attribute is a breaking change, but leaving outside makes it a bit odd if we want to have a consistent API.

**Comment by igitur** [comment]
I agree. I think the `XLColumn` is better. We're still sub v1.0, so I don't really care about a consistent API. The attributes were added fairly recently anyway.

**Comment by albinsunnanbo** [comment]
@igitur I suppose you mean you prefer a consistent API over a stable API at this time?

**Comment by albinsunnanbo** [comment]
You could keep the old attribute for a few releases with an `ObsoleteAttribute` informing about the new API.

**Comment by igitur** [comment]
Not merging this anymore.

**Pull request closed without merging**
