### PR TITLE
Use ClosedXML specific exceptions instead of generic Exception

### PR DESCRIPTION
**Pull request by aakasaka**
Throwing an instance of Exception is a bad practice.
ref: https://msdn.microsoft.com/en-us/library/ms229014(v=vs.100).aspx

### CODE REVIEW

**Comment by igitur** [comment]
Thanks. PR looks good. Would you mind resolving the conflict (after we updated the develop branch). Also check that all exception classes are available in the .NET Standard library.

**Comment by aakasaka** [comment]
Thank you for your reply. I resolved the conflict.
>Also check that all exception classes are available in the .NET Standard library.

I used typical exception classes only, except ExpressionParseException class.
It's an original exception class thrown by CalcEngine.

**Comment by igitur** [comment]
Thanks, so can you confirm that besides `ExpressionParseException` the other exception classes are included in .NET Standard?

**Comment by igitur** [comment]
One more request. Please add a unit test to test that the `ExpressionParseException` is thrown when it should. I don't think it's necessary to unit test the other exceptions.

**Comment by aakasaka** [comment]
>Thanks, so can you confirm that besides ExpressionParseException the other exception classes are included in .NET Standard?

Yes. all the other exceptions are included in .NET Standard.

And I  specified all exception types in test codes.
`ExpressionParseException` is thrown only one place in the tests.
I think it's used just for assertion in the other places.

**Comment by igitur** [comment]
I'd like to include this in v0.89. Can you please fix the conflicts?

**Comment by aakasaka** [comment]
Thanks, I fixed the conflicts.

**Pull request merged**
