### PR TITLE
Pivot table: DateTime type with empty value (Issue #859 fix)

### PR DESCRIPTION
**Pull request by b0bi79**
Issue #859 fix

If the data in the table has data of type DateTime, but there are empty values, ClosedXML specifies containsSemiMixedTypes = "0". In this case, Excel opens such a document with an error: `Excel found unreadable content in 'filename.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.`
To fix this, it need to write containsSemiMixedTypes = "1" for empty datetime values.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks. But please add a unit test.

**Comment by b0bi79** [comment]
Now with test

**Comment by igitur** [comment]
@b0bi79 Sorry, one more thing. Can you please make the commit messages descriptive of the change in the commit?

**Comment by b0bi79** [comment]
I changed the comment to the PR, I don't know how to change the message to the commit. Maybe I can create a new empty commit?

**Comment by igitur** [comment]
It's OK. I squash the 2 commits and entered a new message in the new squash commit.

**Comment by vbjay** [comment]
Read up on interactive rebase.

**Pull request merged**
