### PR TITLE
#598 Fixed some bugs saving pivot table.

### PR DESCRIPTION
**Pull request by b0bi79**
Fixed some bugs saving pivot table, including #598 .

### CODE REVIEW

**Comment by b0bi79** [comment]
@igitur Francois, don't worry. Rest well.

**Comment by b0bi79** [comment]
Fix for #598

**Comment by igitur** [comment]
Just a small note: conflict fixes should actually be part of the same commit as when you merge the branch. Meaning that your last commit should have been part of the 2nd last commit. I'm actually not sure how you managed to merge the develop branch without fixing the conflict.

**Comment by b0bi79** [comment]
I resolved the conflict, and then made a commit. But it was indicated that the file was not the one. I did not understand how it happened.

**Pull request merged**
