### PR TITLE
Escape sheet names with @ in name

### LINKED ISSUE #1331: Worksheet has a print area and the sheet name contains certain symbols, Excel complains to the file saved by ClosedXML.
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

If a worksheet has a print area and the sheet name contains certain symbols, Excel complains to the file saved by ClosedXML.

**What is the expected behavior or new feature?**

Create a file that Excel won't complain.

**Did this work in previous versions of our tool?  Which versions?**

Yes / 0.91.1

## Reproducibility

1. Start Excel and create new workbook.
2. Set print area and rename the sheet "sheet@".
   * This problem occurs when the sheet name contains the following symbols: ~!@#$%(){}.
3. Save the workbook. (test.xlsx)
4. Open and save the file by ClosedXML.
5. Open the file by Excel.
   Excel will say
   "We found a problem with some content in 'test.xlsx'..."
   if select "Yes"
    "Removed Records: Named range from /xl/workbook.xml part (Workbook)"

**Code to reproduce problem:**
```c#
public void Main()
{
            var workbook = new XLWorkbook(@".\.xlsx");
            workbook.Save();
}
```
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/4045237/test.xlsx)

### PR DESCRIPTION
**Pull request by igitur**
Escape sheet names that contain any of a predefined list of characters in name.\

Fixes #1331

### CODE REVIEW

**Comment by souichi-at** [comment]
I'm sorry for my confusing writing.
Please add symbols other than '@' to 'escapeChars'.

I made a xlsx file by Excel 16.0.12325.20280 and opened workbook.xml.
If a sheet name contains any symbols other than '_', it appears to be enclosed in a singlequotation.

```
<definedNames>
    <definedName name="_xlnm.Print_Area" localSheetId="13">'Sheet-'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="2">'Sheet!'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="22">'Sheet"'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="3">'Sheet#'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="4">'Sheet$'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="5">'Sheet%'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="12">'Sheet&amp;'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="6">'Sheet('!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="7">'Sheet)'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="17">'Sheet,'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="18">Sheet.!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="21">'Sheet;'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="0">'Sheet@'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="11">'Sheet^'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="14">Sheet_!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="10">'Sheet`'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="8">'Sheet{'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="23">'Sheet|'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="9">'Sheet}'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="1">'Sheet~'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="15">'Sheet+'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="19">'Sheet&lt;'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="16">'Sheet='!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="20">'Sheet&gt;'!$A$1:$B$3</definedName>
    <definedName name="_xlnm.Print_Area" localSheetId="24">Sheet1!$A$1:$B$3</definedName>
</definedNames>
```

**Comment by Pankraty** [comment]
Ehrm, I believe #1292 must fix this... See the last commit there.

**Comment by souichi-at** [comment]
I confirmed that #1292 fix #1331 .

**Comment by igitur** [comment]
Closed in lieu of #1292

**Pull request closed without merging**
