### PR TITLE
XLWorksheet.Rows() performance is not good if document has >100к rows…

### LINKED ISSUE #1438: XLWorksheet.Rows() performance is not good if document has >100к rows
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**Version of ClosedXML**
Current

**What is the current behavior?**
XLWorksheet.Rows() method works too slowly (3 sec, Intel Core i7) if I open excel file with >100 000 rows 

**What is the expected behavior or new feature?**

Method Rows() should works much faster

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

This is current implementation of XLWorksheet.Rows() method:

```c#
public IXLRows Rows()
        {
            var retVal = new XLRows(this, StyleValue);
            var rowList = new List<Int32>();

            if (Internals.CellsCollection.Count > 0)
                rowList.AddRange(Internals.CellsCollection.RowsUsed.Keys);

            if (Internals.RowsCollection.Count > 0)
                rowList.AddRange(Internals.RowsCollection.Keys.Where(r => !rowList.Contains(r)));

            foreach (int r in rowList)
                retVal.Add(Row(r));

            return retVal;
        }
```

Notice that `rowList` is a `List` and we use `Contains()` in the lambda expression:
`rowList.AddRange(Internals.RowsCollection.Keys.Where(r => !rowList.Contains(r)));`
Obviously that if `rowList` will have 100 000 items or more than `Contains` is very slow. 
It's better for large `Internals.RowsCollection.Keys` collection to declare variable `rowList` as `Dictionary`, not `List`. In this case `rowList.Contains` we will replace to `rowList.ContainsKey` and it will work much faster.

### PR DESCRIPTION
**Pull request by timka3115**
Fixes #1438

### CODE REVIEW

**Comment by igitur** [comment]
Thanks, PR looks good. Do you have any metrics to indicate the performance improvement?

**Comment by igitur** [comment]
If you can attach one of the problematic files, that would be good. Then I can check out the difference in performance.

**Comment by timka3115** [comment]
Ok, no problem. Here is code for performance test:
```c#
using ClosedXML.Excel;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var workbook = new XLWorkbook(@"c:\performance_test.xlsx");
            var watch = System.Diagnostics.Stopwatch.StartNew();
            workbook.Worksheet(1).Rows();
            watch.Stop();
            Console.WriteLine($"Elapsed {watch.ElapsedMilliseconds}ms.");
        }
    }
}
```

My laptop has CPU Intel Core i7, Memory 16Gb.  Before my modification this code print out  9400ms, after performance is dramatically decreased to 17ms.

[performance_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/4664100/performance_test.xlsx)
`

**Comment by igitur** [comment]
Great! Can you please do the same for `Columns()`, `DeleteRow()` and `DeleteColumn()`. Maybe there's even more places in other classes?

**Comment by timka3115** [comment]
> Great! Can you please do the same for `Columns()`, `DeleteRow()` and `DeleteColumn()`? Maybe there's even more places in other classes?

I created a worksheet with 16384 columns (max for Excel) and enumerating Columns() worked fine.  I cannot reproduce case when DeleteRow() and DeleteColumn() works very slowly. The main problem with performance on my side is manipulating with styles for >100000 cells, I will create another ticket. I have an idea how to increase performance here.

**Comment by igitur** [comment]
> > Great! Can you please do the same for `Columns()`, `DeleteRow()` and `DeleteColumn()`? Maybe there's even more places in other classes?
> 
> I created a worksheet with 16384 columns (max for Excel) and enumerating Columns() worked fine. I cannot reproduce case when DeleteRow() and DeleteColumn() works very slowly. The main problem with performance on my side is manipulating with styles for >100000 cells, I will create another ticket. I have an idea how to increase performance here.

I just noticed that those other 3 methods also have `List<Int32>` and thought they could use the same enhancement to use `HashSet<Int32>` rather. 

Must admit, I never knew `List<>.Contains()` was so slow compared to `HashSet<>.Cointains()`

**Comment by makeProjectGreatAgain** [comment]
> I just noticed that those other 3 methods also have `List<Int32>` and thought they could use the same enhancement to use `HashSet<Int32>` rather. Surely the `.Columns()` one can also be changed?

I did the same changes for `.Columns()`.
16384 columns is max for Excel.  There is a very small difference on this size

``` ini

.NET Core SDK=3.1.301
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  DefaultJob : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT


```
|                 Method |          name |                   wb |     Mean |   Error |  StdDev |
|----------------------- |------------------ |--------------------- |---------:|--------:|--------:|
|    **Test_MethodWithList** | **16384Columns.xlsx** | **XLWor(...)xlsx) [48]** | **186.2 ns** | **2.39 ns** | **1.99 ns** |
| Test_MethodWithHashMap | 16384Columns.xlsx | XLWor(...)xlsx) [48] | 183.8 ns | 1.89 ns | 1.77 ns |
|    **Test_MethodWithList** |   **200Columns.xlsx** | **XLWor(...)xlsx) [45]** | **186.6 ns** | **3.24 ns** | **2.88 ns** |
| Test_MethodWithHashMap |   200Columns.xlsx | XLWor(...)xlsx) [45] | 182.6 ns | 1.54 ns | 1.44 ns |
|    **Test_MethodWithList** |    **20Columns.xlsx** | **XLWor(...)xlsx) [44]** | **183.1 ns** | **1.13 ns** | **0.94 ns** |
| Test_MethodWithHashMap |    20Columns.xlsx | XLWor(...)xlsx) [44] | 182.1 ns | 1.10 ns | 1.03 ns |

**Comment by makeProjectGreatAgain** [comment]
> I just noticed that those other 3 methods also have `List<Int32>` and thought they could use the same enhancement to use `HashSet<Int32>` rather. Surely the `.Columns()` one can also be changed?

I did the same changes for `.Columns()`.
The maximum number of columns in a worksheet is 16384.  There is a very small difference on this size

``` ini

.NET Core SDK=3.1.301
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  DefaultJob : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT


```
|                 Method |          name |                   wb |     Mean |   Error |  StdDev |
|----------------------- |------------------ |--------------------- |---------:|--------:|--------:|
|    **Test_MethodWithList** | **16384Columns.xlsx** | **XLWor(...)xlsx) [48]** | **186.2 ns** | **2.39 ns** | **1.99 ns** |
| Test_MethodWithHashMap | 16384Columns.xlsx | XLWor(...)xlsx) [48] | 183.8 ns | 1.89 ns | 1.77 ns |
|    **Test_MethodWithList** |   **200Columns.xlsx** | **XLWor(...)xlsx) [45]** | **186.6 ns** | **3.24 ns** | **2.88 ns** |
| Test_MethodWithHashMap |   200Columns.xlsx | XLWor(...)xlsx) [45] | 182.6 ns | 1.54 ns | 1.44 ns |
|    **Test_MethodWithList** |    **20Columns.xlsx** | **XLWor(...)xlsx) [44]** | **183.1 ns** | **1.13 ns** | **0.94 ns** |
| Test_MethodWithHashMap |    20Columns.xlsx | XLWor(...)xlsx) [44] | 182.1 ns | 1.10 ns | 1.03 ns |

**Comment by igitur** [comment]
@timka3115 @Pankraty What do you think about the changes in 0f6139642ab8829773116fbc22a98ec23fe2ba4e that I added? Is it worth it?

**Review by igitur — APPROVED** [review]

**Comment by timka3115** [comment]
> @timka3115 @Pankraty What do you think about the changes in [0f61396](https://github.com/ClosedXML/ClosedXML/commit/0f6139642ab8829773116fbc22a98ec23fe2ba4e) that I added? Is it worth it?

Yes, it's works a little bit faster for now.

**Pull request merged**
