### PR TITLE
Update DocumentFormat.OpenXml dependency to 2.16.0

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds support up through Office 2019, as well brings a ton of performance/threading fixes under the covers.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks, @twsouthwick . We'd been deliberately avoid a forced upgrade of OpenXML until we required something new in the API, but I think it's becoming clear that the performance improvements make it worth it. The upgrade breaks some tests, which I fixed in 67ad81c9ef3e2e5e582ec62a0e89625203712776.

**Comment by igitur** [comment]
@Pankraty You OK with forcing the upgrade? We'll have to do it for #1619 anyway.

**Comment by Pankraty** [comment]
I agree

**Comment by rominator1983** [comment]
in the meantime you can check out https://github.com/stesee/ClosedXML

**Comment by Havunen** [comment]
Yeah its already 2.15.0 https://www.nuget.org/packages/DocumentFormat.OpenXml/

**Comment by rominator1983** [comment]
Hi. Yes we have included 2.15.0Kind regardsSent from Android deviceAm 25.02.2022 08:11 schrieb Sampo Kivistö ***@***.***>:
Yeah its already 2.15.0 https://www.nuget.org/packages/DocumentFormat.OpenXml/

**Comment by igitur** [comment]
Thanks @twsouthwick. Sorry for the long wait to merge this.

**Pull request merged**
