### PR TITLE
Fix the issue with two root elements appearing on saving

### LINKED ISSUE #1157: XmlException: There are multiple root elements when opening a second time, xlsx with a comment and a button
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.0, also on the latest "develop" branch in Git

**What is the current behavior?**

When opening a spreadsheet with a comment and a button, saving and, and opening again, it crashes with System.Xml.XmlException.

**What is the expected behavior or new feature?**

Open a second time without issues.

**Did this work in previous versions of our tool?  Which versions?**

Don't know

## Reproducibility
(a sample spreadsheet with this problem is attached)
1. Open Excel 2010
2. Add a comment (from the Review tab, "New Comment")
3. Add a button (from the Developer tab, Insert->"Button (Form Control)"
4. Save the spreadsheet as BaseFile.xlsx
5. Run the program provided below.
6. Observe that on the second call to "new XLWorkbook(tempFile)", the program crashes with the following exception:
`System.Xml.XmlException: There are multiple root elements. Line 23, position 19.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
   at ClosedXML.Excel.XDocumentExtensions.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook.GetCommentVmlFile(WorksheetPart wsPart)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at Bug.Program.Main(String[] args) in C:\Users\erezw\Source\Repos\ClosedXML\Bug\Program.cs:line 24`
**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
using System;
using System.IO;

namespace Bug
{
    class Program
    {
        static void Main(string[] args)
        {
            string baseFile = "BaseFile.xlsx";
            string tempFile = "Temp.xlsx";
            File.Copy(baseFile, tempFile, true);
            XLWorkbook workbook;

            // First open, succeeds
            workbook = new XLWorkbook(tempFile);
            workbook.Save();

            try
            {
                // Second open, fails with
                //System.Xml.XmlException: There are multiple root elements. Line 23, position 19.
                workbook = new XLWorkbook(tempFile);
            }
            catch (System.Xml.XmlException ex)
            {
                Console.WriteLine("Here, a bug!" + ex.ToString());
                return;
            }
            catch (Exception)
            {
                Console.WriteLine("Another exception? This doesn't happen");
                return;
            }
            workbook.Save();
            Console.WriteLine("No bug");
        }
    }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BaseFile.xlsx](https://github.com/ClosedXML/ClosedXML/files/2952842/BaseFile.xlsx)

### LINKED ISSUE #1203: Saving WorkBook with button and macro unlinks macro from button
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

After saving a XLSM with button and macro, the link of the button to the macro gets lost.

**What is the expected behavior or new feature?**

The connection of the macro to the button should remain vaild.

**Did this work in previous versions of our tool?  Which versions?**

Not sure.

## Reproducibility

1) open excel with Macro/Button
2) do some changes
3) Save and close excel with Macro/Button

When opened in Excel application, the button "Toggle Rowfilter" can not be clicked as the link to the macro is lost.

**Code to reproduce problem:**
```c#
using (var xlWorkBook = new XLWorkbook(FileName, XLEventTracking.Disabled))
{
    IXLWorksheet xlWorkSheet = xlWorkBook.Worksheets.FirstOrDefault();
    IXLRange range = xlWorkSheet.RangeUsed();
    // do changes in WorkSheet
    xlWorkBook.Save();
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Button.zip](https://github.com/ClosedXML/ClosedXML/files/3285925/Button.zip)

### PR DESCRIPTION
**Pull request by Pankraty**
Fixes #1157 
Fixes #1203

I believe the bug was in a `GenerateVmlDrawingPartContent` method. As I understood the intention of the original developer, the original `stream` was copied to a memory stream `ms` to keep the data from erasing, then the `writer` created a new root element and wrote the data there. In the end, the original data from `ms` was written back to `stream`.

But due to an unfortunate mistake, the wrong stream was reset to zero position. Another call to `ms.Position = 0;` a few lines below confirms this. Since `stream` was not reset, the new root element was added to the end of the stream - that's what caused the exception during the opening.

### CODE REVIEW

**Comment by Pankraty** [comment]
I think this can be safely included in 0.95.

**Comment by igitur** [comment]
I have a WIP fix for this too. So I want to confirm my approach to yours first. Most of the VML stuff was by trying to reverse engineer the XML anyway, so not surprising that it's buggy.

**Comment by igitur** [comment]
Ok, I remember now. When I started digging into this issue I noticed that `DeleteComments()` does some weird things. It renames and deletes the original vmlDrawingPart and creates a new one. I dislike this as it means opening and saving a file without modification leads to a change in the part's ID. I wanted to fix that first before addressing #1157  further as they are related.

**Comment by igitur** [comment]
I think #1227 should supercede this.

**Comment by igitur** [comment]
Superceded by #1227

**Pull request closed without merging**
