### PR TITLE
Disposing of operating ranges.

### PR DESCRIPTION
**Pull request by b0bi79**
Added Dispose call where it was missed. For large documents, this is critically important. Otherwise, callback lists grow by tens and hundreds of thousands, which leads to the freezing of the application.

### CODE REVIEW

**Comment by igitur** [comment]
Does this fix #165 ?

**Comment by igitur** [comment]
PS: The recommended way to do changes is to branch on your side first (`git checkout -b newbranchname upstream/develop`), make the changes, push to your local repo (`git push origin newbranchname`) and then creating the PR. 

The way you did it now makes it difficult for you to work on a separate feature until this PR is merged into the `develop` branch.

**Comment by igitur** [comment]
I think there are many more places where the `using` statement has to be used for ranges.

**Comment by b0bi79** [comment]
No, this is not a fix for #165 .
Yes, there are certainly more places where the `using` statement has to be used. If you want, I'll find all these places and correct them. Now I have found the most frequently used places.

Thanks for the help with the git.

**Comment by igitur** [comment]
Please see if #521 improves performance. Also, if you can attach an example of the large spreadsheet and the operations you do on it, it would be nice. Then I can test the performance myself.

**Pull request merged**
