### PR TITLE
Added '[' as a valid character to begin Named Ranges

### LINKED ISSUE #1011: When workbook contains NamedRange starting with "[" the workbook can't be opened. Exception message is "The named range name '\y' does not begin with a letter or an underscore"
**Do you want to request a *feature* or report a *bug*?**
- [x ] Bug

**Version of ClosedXML**
0.93.1

**What is the current behavior?**

When opening the workbook, ClosedXml crashes.

**What is the expected behavior or new feature?**

It's possible to create a named range starting with "[" in excel. ClosedXml should be able to open a spreadsheet using this format.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
   var wb = new XLWorkbook("Test Workbook.xlsx");
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Test Workbook.xlsx](https://github.com/ClosedXML/ClosedXML/files/2425615/Test.Workbook.xlsx)

### PR DESCRIPTION
**Pull request by MexicanCustard**
#### What's this PR do?
Added '[' as a valid starting character in named ranges (fixes #1011)

### CODE REVIEW

**Comment by Pankraty** [comment]
Hmm, the logic in Excel seems to be more complicated. 
`[test` - invalid
`[test]` - invalid
`[test]1` - invalid
`[test]test1` - **valid**
`[test][test]test` - invalid
`[test]test]test` - invalid
`test[test]test` - invalid
`[]test` - invalid
`[ ]test` - invalid
`[_]test` - **valid**
`[123]test` - **valid**
`[ 123]test` - invalid

So the named range title may only have square brackets if and only if 
1) there is a single pair of square brackets
2) the named range name starts with the `[`
3) the expression in brackets contains letters, digits, `_` or `\`
4) the expression after the brackets contains letters, digits, `_` or `\` and does not start with a digit.

**Comment by igitur** [comment]
Is there any documentation available about what the exact rules are for named ranges' names? Maybe we should peak into LibreOffice's source code?

**Comment by igitur** [comment]
Interesting. LibreOffice does not allow this.

**Comment by igitur** [comment]
Superceded by #1036

**Pull request closed without merging**
