### PR TITLE
Support TargetFramework with a lower version (4.0)

### PR DESCRIPTION
**Pull request by Pankraty**
Related pull request #650 

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by Pankraty** [comment]
Both, actually... Yes, there are changes I wish to merge (7 changed files), and yes, there are non-related commits too. All commits in the list except the last have nothing to do with the PR, but changes from them are not included.

The most annoying is that I have spent a few minutes for changing the code and a few hours fighting with Git ( Probably I should simply re-fork the repo again and next time do everything right from the beginning.

**Comment by vbjay** [comment]
No.  There is no need to re fork.  

First reset this branch to upstream/develop(our develop)  Then cherry pick in order of adding the commits to the branch the commits you want in this branch.  You will have to then force push this branch to update it on github.  Then create other branches for other work and do the same.  Then reset your develop to our upstream develop.  Don't do work on develop.  Do work in branches off of develop.

**Comment by vbjay** [comment]
http://gitextensions.github.io/ is a good gui for git.

**Comment by vbjay** [comment]
If you want help with doing this, you can email me your teamviewer id and password, and I can show you what I mean.   Also.  http://www.vogella.com/tutorials/Git/article.html is a really good tutorial to learn different git concepts.

**Comment by Pankraty** [comment]
Thank you for being ready to help! #660 seems fine so I am closing this PR.

**Pull request closed without merging**
