### PR TITLE
Fix issues occurred when running tests on .Net Core 3.0

### LINKED ISSUE #1273: Date formatting does not support AM/PM designation from C# format
## Read and complete the full issue template

- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95 beta2

**What is the current behavior?**

If you set a date format for a cell to this:

M/d/yyyy h:mm:ss tt

it simply returns the format string when you call GetFormattedString() on the cell. If you load the Excel the date is formatted like so:

10/16/2017 15:05:00 tt

rather than the correct value of:

10/16/2017  3:05:00 PM

**What is the expected behavior?**

It should convert to the format to the AM/PM format style used by Excel, and correctly format it both in the resulting Excel file and when you call GetFormattedString().

**Did this work in previous versions of our tool?  Which versions?**

Yes

Not sure which version, it was broke in 0.90.0 so I suspect a version prior to that. My unit test used to pass, but now it does not.

## Reproducibility

Please see:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelWriterTests.cs

uncomment line 127 and run run WriteCellTest(). It will fail. Attached is the Excel file generated for the test, but you can also generate it to a temp directory by defining WRITE_TEST_FILE when you build the code.

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3526733/test.xlsx)

### LINKED ISSUE #1274: Long date formatting produces incorrect result in GetFormattedString()
## Read and complete the full issue template

- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95 beta2

**What is the current behavior?**

If you set a date format for a cell to this:

dddd, MMMM d, yyyy

when you call GetFormattedString() on the cell it drops all the commas. If you load the Excel the date is formatted like so:

Monday, October 16, 2017

but GetFormattedString() returns this:

Monday October 16 2017

**What is the expected behavior?**

It should not drop the commas.

**Did this work in previous versions of our tool?  Which versions?**

Yes, it worked correctly in 0.90 and I noticed in broken in 0.94.2 and 0.95 beta2.

## Reproducibility

Please see:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelWriterTests.cs

uncomment line 135 and run run WriteCellTest(). It will fail. Attached is the Excel file generated for the test, but you can also generate it to a temp directory by defining WRITE_TEST_FILE when you build the code.

[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3526760/test.xlsx)

### LINKED ISSUE #1318: When tests are run with netcoreapp3.0 there are test failures
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

Latest develop

**What is the current behavior?**

There are multiple tests failing after changing test project's target from netcoreapp2.0 to netcoreapp3.0.

**What is the expected behavior or new feature?**

The library should work with both .NET Core 2.x and 3.x.

**Did this work in previous versions of our tool?  Which versions?**

Unsure.

## Reproducibility

Change ClosedXml_Tests.csproj:

`<TargetFrameworks>netcoreapp3.0;net40;net46</TargetFrameworks> `

and 
```
<PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
  <DefineConstants>$(DefineConstants);_NETSTANDARD_;_NETSTANDARD2_0_</DefineConstants>
</PropertyGroup>
```

Run tests and get following errors:

```
Test run for C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\bin\Release\netcoreapp3.0\ClosedXML_Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X CellValues [106ms]
  Error Message:
     Actual file 'C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\bin\Release\netcoreapp3.0\Generated\Examples\Misc\CellValues.xlsx' is different than the expected file 'Examples.Misc.CellValues.xlsx'. The difference is: '/xl/sharedStrings.xml :NonEqual
/xl/worksheets/sheet1.xml :NonEqual
'
  Expected: True
  But was:  False

  Stack Trace:
     at ClosedXML_Tests.TestHelper.RunTestExample[T](String filePartName, Boolean evaluateFormulae) in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\TestHelper.cs:line 93
   at ClosedXML_Tests.Examples.MiscTests.CellValues() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Examples\MiscTests.cs:line 56

  X DataTypes [72ms]
  Error Message:
     Actual file 'C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\bin\Release\netcoreapp3.0\Generated\Examples\Misc\DataTypes.xlsx' is different than the expected file 'Examples.Misc.DataTypes.xlsx'. The difference is: '/xl/sharedStrings.xml :NonEqual
/xl/worksheets/sheet1.xml :NonEqual
'
  Expected: True
  But was:  False

  Stack Trace:
     at ClosedXML_Tests.TestHelper.RunTestExample[T](String filePartName, Boolean evaluateFormulae) in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\TestHelper.cs:line 93
   at ClosedXML_Tests.Examples.MiscTests.DataTypes() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Examples\MiscTests.cs:line 80

  X DataTypesUnderDifferentCulture [95ms]
  Error Message:
     Actual file 'C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\bin\Release\netcoreapp3.0\Generated\Examples\Misc\DataTypesUnderDifferentCulture.xlsx' is different than the expected file 'Examples.Misc.DataTypesUnderDifferentCulture.xlsx'. The difference is: '/xl/sharedStrings.xml :NonEqual
/xl/worksheets/sheet1.xml :NonEqual
'
  Expected: True
  But was:  False

  Stack Trace:
     at ClosedXML_Tests.TestHelper.RunTestExample[T](String filePartName, Boolean evaluateFormulae) in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\TestHelper.cs:line 93
   at ClosedXML_Tests.Examples.MiscTests.DataTypesUnderDifferentCulture() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Examples\MiscTests.cs:line 86

  X Sorting [248ms]
  Error Message:
     Actual file 'C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\bin\Release\netcoreapp3.0\Generated\Examples\Ranges\Sorting.xlsx' is different than the expected file 'Examples.Ranges.Sorting.xlsx'. The difference is: '/xl/worksheets/sheet5.xml :NonEqual
/xl/worksheets/sheet7.xml :NonEqual
'
  Expected: True
  But was:  False

  Stack Trace:
     at ClosedXML_Tests.TestHelper.RunTestExample[T](String filePartName, Boolean evaluateFormulae) in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\TestHelper.cs:line 93
   at ClosedXML_Tests.Examples.RangesTests.Sorting() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Examples\RangesTests.cs:line 87

  X ChangingDataTypeChangesCachedValue [4ms]
  Error Message:
     Expected string length 17 but was 19. Strings differ at index 17.
  Expected: "0.158333333333333"
  But was:  "0.15833333333333333"
  ----------------------------^

  Stack Trace:
     at ClosedXML_Tests.Excel.CalcEngine.FormulaCachingTests.ChangingDataTypeChangesCachedValue() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Excel\CalcEngine\FormulaCachingTests.cs:line 385

  ! Validation_3 [< 1ms]
  ! Validation_5 [< 1ms]
  ! NamedRangeBecomesInvalidOnRangeAndWorksheetDeleting [< 1ms]
  ! NamedRangeBecomesInvalidOnRangeDeleting [< 1ms]
  ! SetPackagePropertiesEntryToNullWithOpenXml [< 1ms]
  X Nan_is_not_a_number [1ms]
  Error Message:
     Expected: not equal to Number
  But was:  Number

  Stack Trace:
     at ClosedXML_Tests.XLCellTests.Nan_is_not_a_number() in C:\Work\OpenSource\ClosedXML\ClosedXML_Tests\Excel\Cells\XLCellTests.cs:line 241

  ! CopyWorksheetChangesAbsoluteReferencesInFormulae [< 1ms]
  ! RenameWorksheetChangesAbsoluteReferencesInFormulae [< 1ms]

Total tests: 2596
     Passed: 2583
     Failed: 6
    Skipped: 7
 Total time: 23,9091 Seconds

```

### PR DESCRIPTION
**Pull request by Pankraty**
Fixes #1318

Fixes #1273

Fixes #1274 

One test is still failing due to andersnm/ExcelNumberFormat#23.

@igitur should we switch to `netcoreapp3.0` in tests or add it as a new target (the 4th one)?

### CODE REVIEW

**Comment by igitur** [comment]
> should we switch to `netcoreapp3.0` in tests or add it as a new target (the 4th one)?

I think switch to `netcoreapp3.0`

**Comment by igitur** [comment]
Or maybe `netcoreapp3.1` as `netcoreapp3.0` is very soon obsoleted.

**Comment by Pankraty** [comment]
Ready for review

**Comment by igitur** [comment]
Please rebase and make extension changes in both `ObjectToInvariantString` and `ToInvariantString<T>`

**Comment by Pankraty** [comment]
Done

**Pull request merged**
