### PR TITLE
ClosedXML recent packages' updates

### PR DESCRIPTION
**Pull request by DonPatch74**
Firstly, I wanted to say say huge thank you for the package that you have provided. Very great piece of software that helps with spreadsheets.

Secondly, I noticed that security solution (SNYK) I use for my application pointed out few issues, which are only related to packages used by ClosedXML. I have pulled the branch and updated everything just to make sure that will be resolved and it occured that this simple procedure fixed everything.

Please check the updated packages and if it is okay merge it, so I could keep using the ClosedXML as nuget package instead of exporting it ito bunch of dll files.

Kindest regards,
Ben

### CODE REVIEW

**Comment by jahav** [comment]
Please be more specific about the issues. Just blanket update won't work (e.g. every change in XLParser is also change in grammar, i.e. breaking change) and as a library, I generally go for lower versions, see also https://github.com/ClosedXML/ClosedXML/pull/1950#issuecomment-1371689496

**Comment by DonPatch74** [comment]
Sure thing, this is the list of the security vulnerabilities found by our security provider:

- Regular Expression Denial of Service (ReDoS)
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Xml.XDocument@4.3.0 > System.Xml.ReaderWriter@4.3.0 > System.Text.RegularExpressions@4.3.0

- Information Exposure
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0

- Privilege Escalation
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0

- Improper Certificate Validation
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0

- Denial of Service (DoS)
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0

- Authentication Bypass
Introduced through ClosedXML@0.100.3 > XLParser@1.5.2 > Irony.NetCore@1.0.11 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0

Please let me know if there is anything else to provide.

**Comment by jahav** [comment]
These are all minimal versions from NETStandard.Library. 

Netstandard is only a specification of API, not an implementation. At least for core, application doesn't use minimal version, but the current implementation from .NET Core of the application (e.g. 7 for net7).

When I look at the discussion in .NET Standard repo, they say basically same thing (aka false positive): https://github.com/dotnet/standard/issues/1786

> System.Text.RegularExpressions never applies a vulnerable binary on .NETFramework. It applies a facade dll that typeforwards to System.dll where all this code lives. The facade dll is not vulnerable as it does not contain the code. System.Text.RegularExpressions also does not apply its binary on .NETCore2.0 and later. There the implementation is provided by the shared framework. This package only exists for delivering the implementation to older frameworks (.netcore1.x), which are now out of support.

Also, updating packages won't solve anything, because they will still reference netstandard 1.6.1 (thus transitively minimal 4.3.0 versions).

This is only security issue, if you run retired framework/core (e.g. 4.5 or core2), so I consider it to be a false positive.

**Comment by DonPatch74** [comment]
Thank you for the explanation. Then, I am gonna use our upgraded version and keep on checking for any updates.

**Pull request closed without merging**
